export const JLG742_COMPONENTS = Object.freeze({
  chassis: Object.freeze({ title: "Load-bearing chassis", eyebrow: "5.76 m less forks · published", body: "The reconstruction separates the frame, counterweight, belly protection, engine-side bodywork, tanks, steps and fenders. Small panel dimensions and sheet profiles are independent visual reconstruction.", facts: [["Published envelope", "5.76 m length less forks · 2.46 m width"], ["Visual systems", "Frame · counterweight · guards · bodywork"], ["Boundary", "Panel profiles reconstructed from public views"]] }),
  cab: Object.freeze({ title: "Open operator cab", eyebrow: "PVC 2411 · verified branch", body: "The no-option freeze uses the current open-cab branch. Seat, wheel, joystick, display, pedals, mirrors, glazing, ROPS/FOPS members and roof guard are represented for identification, not control training.", facts: [["Frozen branch", "Open cab · no selected options"], ["Visible cues", "Seat · controls · mirrors · roof guard"], ["Boundary", "Identification only · not operator training"]] }),
  boom: Object.freeze({ title: "Three-section boom", eyebrow: "First / second / third · verified", body: "PVC 2411 identifies three boom section assemblies plus extend and retract chains and sheaves. Displayed section strokes, overlap, wear-pad locations and hose paths are explicitly reconstructed inside the public envelope.", facts: [["Published topology", "Three boom section assemblies"], ["Published envelope", "12.8 m lift height · 8.86 m forward reach"], ["Reconstructed", "Section staging · overlap · hose paths"]] }),
  carriage: Object.freeze({ title: "50-inch floating carriage", eyebrow: "Standard attachment freeze", body: "The frozen attachment is the 1.27 m standard fully floating carriage with the first listed 1.2 m pallet-fork choice. The tilt interaction is presentational and does not model a load or hydraulic response.", facts: [["Carriage", "1.27 m standard fully floating"], ["Forks", "1.2 m pallet-fork choice"], ["Boundary", "No load or hydraulic response simulated"]] }),
  steering: Object.freeze({ title: "Three steering modes", eyebrow: "Circle / crab / front · verified", body: "JLG publishes selectable four-wheel circle, four-wheel crab and two-wheel front steering. The browser shows each topology; its inner/outer wheel angles are reconstructed, not a factory steering curve.", facts: [["Published modes", "Circle · crab · front"], ["Visible system", "Four steering pivots and linkage cues"], ["Reconstructed", "Wheel-angle relationship · not a factory curve"]] }),
  hydraulics: Object.freeze({ title: "Visible hydraulic systems", eyebrow: "PVC 2411 topology", body: "Lift, telescope, steering, carriage and frame-level cylinder cues are separated from hose and valve-bank materials. Routing, bore, pressure, timing and interlocks are outside this visual study.", facts: [["Represented", "Lift · telescope · steer · tilt · frame level"], ["Visual cues", "Cylinder bodies · rods · hoses · valve bank"], ["Excluded", "Pressure · timing · interlocks · service routing"]] }),
  frame: Object.freeze({ title: "Frame leveling hierarchy", eyebrow: "10 degrees · published limit", body: "The chassis, cab and boom roll independently of the ground-running gear up to the published visual limit. Rear-axle stabilization modes and safe-use conditions are intentionally not simulated.", facts: [["Published visual limit", "10° frame leveling"], ["Hierarchy", "Upper frame rolls over ground-running gear"], ["Excluded", "Stability logic · safe-use conditions"]] }),
  about: Object.freeze({ title: "Evidence-bound 742", eyebrow: "Owned reconstruction · PVC 2411", body: "Current specification, matched manuals, gallery views and temporary BIM references informed this independently authored asset. No manufacturer geometry, image, decal artwork or manual binary is deployed.", facts: [["Configuration", "72 hp · open cab · 370/75-28 tires"], ["Attachment", "50 in floating carriage · 48 in pallet forks"], ["Boundary", "Independent visual reconstruction only"]] }),
});
