export const ES1930M_COMPONENTS = Object.freeze({
  about: Object.freeze({ title: "PVC 2404, reconstructed honestly.", eyebrow: "Evidence boundary", body: "Current JLG parts, service and operation publications establish the machine identity, five-level topology and performance envelope. Unpublished pivot coordinates remain labeled reconstruction.", facts: [["Model", "ES1930M standard ANSI/US configuration"], ["Primary set", "Parts 3122602400 · Service 3122602300 · Operation 3122602200"], ["Boundary", "Not a service, training, fabrication, stability, or safety reference"]] }),
  chassis: Object.freeze({ title: "Compact chassis", eyebrow: "PVC 2404 · verified envelope", body: "The 30 in-wide chassis packages two 12 V 130 Ah flooded batteries, electric wheel drive, hydraulic steering, active pothole protection, ground controls and leak containment.", facts: [["Width", "0.76 m / 30 in"], ["Length", "1.48 m / 57.8 in"], ["Mass", "1,351 kg / 2,978 lb nominal"]] }),
  scissor: Object.freeze({ title: "Rear-pinned five-level stack", eyebrow: "PVC 2404 · verified topology", body: "The rear end is frame-pinned while a lateral pair of lower blocks travels in the front slide channel. The matching upper pin/slide assignment and all fabrication coordinates are explicitly reconstructed.", facts: [["Levels", "5 verified arm levels"], ["Lower travel", "Rear fixed · two front slide blocks"], ["Coordinate authority", "Reconstruction Hypothesis H1"]] }),
  lift_cylinder: Object.freeze({ title: "Cylinder and ternary kicker", eyebrow: "685.5 ± 1.5 mm stroke · verified", body: "The cylinder, three-axis kicker and lower scissor stage now form one connected presentation graph. Exact attachment coordinates and roller-contact leverage remain Reconstruction Hypothesis H1.", facts: [["Cylinder", "Single acting"], ["Published stroke", "685.5 ± 1.5 mm"], ["Graph", "Cylinder → kicker → scissor"]] }),
  extension_deck: Object.freeze({ title: "Extension deck", eyebrow: "0.55 m travel · verified", body: "The foot-actuated deck moves 21.6 in and carries a published 254 lb capacity within the machine's 500 lb total capacity. Only its attached deck and rail branch translates." }),
  steering: Object.freeze({ title: "Hydraulic front steering", eyebrow: "80 mm each direction · angle deferred", body: "One double-rod cylinder joins both drive-wheel spindles. The verified actuator travel is shown, while wheel-angle motion stays neutral until a PVC 2404 spindle/link graph can be reconciled.", facts: [["Actuator travel", "80 mm each direction"], ["Inside radius", "0 m published"], ["Wheel angles", "Deferred; not invented"]] }),
  pothole: Object.freeze({ title: "Active pothole protection", eyebrow: "Verified topology and clearances", body: "Linked protection bars deploy as the platform rises. Published clearance changes from 2.4 in retracted to 1.0 in deployed; linkage coordinates are reconstructed." }),
  platform: Object.freeze({ title: "Standard platform", eyebrow: "52.8 × 27.6 in · verified", body: "The frozen standard platform supports two occupants indoors or one outdoors, with fixed rails, self-closing gate and current ANSI control station." }),
  controls: Object.freeze({ title: "Machine controls", eyebrow: "Operation manual · PVC 2404", body: "Platform and ground stations are represented for identification. The showcase does not simulate authorization, interlocks, emergency descent, load sensing or safe operating procedure." }),
});
