export const ES1930M_COMPONENTS = Object.freeze({
  chassis: Object.freeze({ title: "Compact chassis", eyebrow: "PVC 2404 · verified envelope", body: "The 30 in-wide chassis packages two 12 V 130 Ah flooded batteries, electric wheel drive, hydraulic steering, active pothole protection, ground controls and leak containment." }),
  scissor: Object.freeze({ title: "Five-level scissor stack", eyebrow: "PVC 2404 · verified topology", body: "Ten identified inboard/outboard arm groups close through explicit pivots. Link lengths and anchor coordinates in this browser reconstruction are authored, because JLG does not publish fabrication coordinates." }),
  lift_cylinder: Object.freeze({ title: "Single-acting lift cylinder", eyebrow: "685.5 mm stroke · verified", body: "Hydraulic pressure extends the cylinder; gravity retracts it. The displayed 685.5 mm pin-distance change is verified, while installation coordinates and kicker leverage remain reconstructed." }),
  extension_deck: Object.freeze({ title: "Extension deck", eyebrow: "0.55 m travel · verified", body: "The foot-actuated deck moves 21.6 in and carries a published 254 lb capacity within the machine's 500 lb total capacity. Only its attached deck and rail branch translates." }),
  steering: Object.freeze({ title: "Hydraulic front steering", eyebrow: "80 mm each direction · mixed authority", body: "One double-rod cylinder joins both drive-wheel spindles. Cylinder stroke and turning-radius envelope are published; displayed spindle angles are explicitly reconstructed, not a factory steering curve." }),
  pothole: Object.freeze({ title: "Active pothole protection", eyebrow: "Verified topology and clearances", body: "Linked protection bars deploy as the platform rises. Published clearance changes from 2.4 in retracted to 1.0 in deployed; linkage coordinates are reconstructed." }),
  platform: Object.freeze({ title: "Standard platform", eyebrow: "52.8 × 27.6 in · verified", body: "The frozen standard platform supports two occupants indoors or one outdoors, with fixed rails, self-closing gate and current ANSI control station." }),
  controls: Object.freeze({ title: "Machine controls", eyebrow: "Operation manual · PVC 2404", body: "Platform and ground stations are represented for identification. The showcase does not simulate authorization, interlocks, emergency descent, load sensing or safe operating procedure." }),
});
