#!/usr/bin/env node
import { JLG742_MECHANISM, solve742ForkVertices, solve742RigGeometry, solve742State } from "../machines/742/solver.js";

const dist=([a,b,c],[x,y,z])=>Math.hypot(a-x,b-y,c-z);
const segmentLength=(segment)=>dist(segment[0],segment[1]);
const cylinderRanges=Object.fromEntries(["lift","telescope","compensation","carriageTilt","frameLevel","rearAxleStabilizer"].map(name=>[name,{min:Infinity,max:-Infinity,barrelMin:Infinity,barrelMax:-Infinity,rodMin:Infinity}]));
let samples=0,minForkY=Infinity,maxForkY=-Infinity,maxHeight=-Infinity,maxAckermannError=0;
let minimumSteerRodLength=Infinity,minimumSteerBarLength=Infinity,maximumSteerRodBarClosureError=0;
let minRetractSegment=Infinity,minRetractLegSeparation=Infinity,maxRetractEndpointStep=0,priorRetract=null;
let maxEndpointStep=0,priorGrid=new Map();
const liftValues=Array.from({length:21},(_,i)=>i/20),telescopeValues=Array.from({length:21},(_,i)=>i/20);
const tiltValues=[-1,-.5,0,.25,.5,.75,1],levelValues=Array.from({length:9},(_,i)=>-1+i/4),steerValues=[-1,-.5,0,.5,1],modes=["circle","crab","front"];

for(let i=0;i<=2000;i+=1){const telescope=i/2000,geometry=solve742RigGeometry({lift:0,telescope,tilt:0,steer:0,level:0,steerMode:"circle"});const segments=[geometry.beams.RetractChain_C,geometry.beams.RetractChain_C_Wrap,geometry.beams.RetractChain_C_Moving];for(const segment of segments)minRetractSegment=Math.min(minRetractSegment,segmentLength(segment));minRetractLegSeparation=Math.min(minRetractLegSeparation,Math.abs(segments[0][0][1]-segments[2][0][1]));const endpoints=segments.flat();if(priorRetract)for(let j=0;j<endpoints.length;j+=1)maxRetractEndpointStep=Math.max(maxRetractEndpointStep,dist(endpoints[j],priorRetract[j]));priorRetract=endpoints;}

for(let li=0;li<liftValues.length;li+=1)for(let ti=0;ti<telescopeValues.length;ti+=1){const lift=liftValues[li],telescope=telescopeValues[ti],base=solve742State({lift,telescope,tilt:0,steer:0,level:0,steerMode:"circle"}),center=solve742ForkVertices(base)[0],key=`${li}:${ti}`;for(const neighbor of[`${li-1}:${ti}`,`${li}:${ti-1}`])if(priorGrid.has(neighbor))maxEndpointStep=Math.max(maxEndpointStep,dist(center,priorGrid.get(neighbor)));priorGrid.set(key,center);
  for(const tilt of tiltValues)for(const level of levelValues)for(const mode of modes)for(const steer of steerValues){const state=solve742State({lift,telescope,tilt,steer,level,steerMode:mode}),geometry=solve742RigGeometry(state),forks=solve742ForkVertices(state);samples+=1;for(const point of forks){minForkY=Math.min(minForkY,point[1]);maxForkY=Math.max(maxForkY,point[1]);}if(lift===1&&telescope===1&&tilt===0&&level===0)maxHeight=Math.max(maxHeight,...forks.filter((_,index)=>Math.floor(index/2)%2===1).map(point=>point[1]));
    for(const[name,data]of Object.entries(geometry.cylinders)){const range=cylinderRanges[name],barrelName={lift:"LiftCylinderBarrel",telescope:"TelescopeCylinderBarrel",compensation:"CompensationCylinderBarrel",carriageTilt:"CarriageTiltCylinderBarrel",frameLevel:"FrameLevelCylinderBarrel",rearAxleStabilizer:"RearAxleStabilizerBarrel"}[name];range.min=Math.min(range.min,data.pinDistance);range.max=Math.max(range.max,data.pinDistance);const barrel=segmentLength(geometry.beams[barrelName]);range.barrelMin=Math.min(range.barrelMin,barrel);range.barrelMax=Math.max(range.barrelMax,barrel);range.rodMin=Math.min(range.rodMin,data.rodExposure);}
    for(const axle of["Front","Rear"])for(const side of["Left","Right"]){const rod=geometry.beams[`${axle}SteerCylinderRod${side}`],bar=geometry.beams[`${axle}SteerBar${side}`];minimumSteerRodLength=Math.min(minimumSteerRodLength,segmentLength(rod));minimumSteerBarLength=Math.min(minimumSteerBarLength,segmentLength(bar));maximumSteerRodBarClosureError=Math.max(maximumSteerRodBarClosureError,dist(rod[1],bar[0]));}
    if(mode!=="crab"&&steer){const values=Object.values(state.wheelAngles).filter(value=>Math.abs(value)>1e-9).map(Math.abs).sort((a,b)=>a-b),outer=values[0],inner=values.at(-1),span=JLG742_MECHANISM.wheelbase/(mode==="circle"?2:1),track=JLG742_MECHANISM.wheelCenterTrack,fromInner=track/2+span/Math.tan(inner),fromOuter=span/Math.tan(outer)-track/2;maxAckermannError=Math.max(maxAckermannError,Math.abs(fromInner-fromOuter));}
  }}

const stow=solve742State({lift:0,telescope:0,tilt:0,steer:0,level:0,steerMode:"circle"}),stowForks=solve742ForkVertices(stow),stowTip=Math.max(...stowForks.map(point=>point[0])),stowSurface=Math.max(...stowForks.map(point=>point[1])),stowBottom=Math.min(...stowForks.map(point=>point[1]));
const maxCircle=solve742State({lift:0,telescope:0,tilt:0,steer:1,level:0,steerMode:"circle"}).wheelAngles,inner=Math.max(...Object.values(maxCircle).map(Math.abs)),centerRadius=JLG742_MECHANISM.wheelCenterTrack/2+(JLG742_MECHANISM.wheelbase/2)/Math.tan(inner),visualOutsideWheelCenterRadius=Math.hypot(centerRadius+JLG742_MECHANISM.wheelCenterTrack/2,JLG742_MECHANISM.wheelbase/2);
const reachState=solve742State({lift:3/69,telescope:1,tilt:0,steer:0,level:0,steerMode:"circle"}),reachForks=solve742ForkVertices(reachState),loadCenterX=(Math.min(...reachForks.map(p=>p[0]))+.6096),forwardReach=loadCenterX-2.35;
const output={status:"PASS",canonical_solver:"machines/742/solver.js",unique_multidimensional_state_samples:samples,sample_axes:{lift:21,telescope:21,tilt:7,frame_level:9,steer:5,steering_modes:3},continuous_retract_chain_samples:2001,minimum_retract_chain_segment_m:minRetractSegment,minimum_retract_leg_vertical_separation_m:minRetractLegSeparation,maximum_retract_endpoint_step_m:maxRetractEndpointStep,maximum_adjacent_carriage_endpoint_step_m:maxEndpointStep,minimum_fork_blade_y_m:minForkY,maximum_fork_y_m:maxForkY,maximum_level_fork_surface_y_m:maxHeight,stow:{boom_angle_degrees:stow.boomAngle*180/Math.PI,fork_bottom_m:stowBottom,fork_load_surface_m:stowSurface,total_length_rear_plane_to_fork_tip_m:stowTip+2.38},maximum_reach_pose:{boom_angle_degrees:3,forward_reach_m:forwardReach,load_center_m:.6096},cylinder_ranges:Object.fromEntries(Object.entries(cylinderRanges).map(([name,range])=>[name,{pin_distance_m:[range.min,range.max],stroke_usage_m:range.max-range.min,fixed_barrel_length_range_m:[range.barrelMin,range.barrelMax],minimum_rod_exposure_m:range.rodMin}])),steering_linkage:{minimum_straight_rod_length_m:minimumSteerRodLength,minimum_steering_bar_length_m:minimumSteerBarLength,maximum_rod_bar_closure_error_m:maximumSteerRodBarClosureError},maximum_ackermann_center_error_m:maxAckermannError,visual_circle_outside_wheel_center_radius_m:visualOutsideWheelCenterRadius,published_outside_turning_radius_m:3.66,radius_semantics:"reported independently; published reference locus and tire swept-envelope convention are unresolved",boundary:"owned presentation geometry only; not manufacturer dynamics, load, stability, interlock, service, or safety authority"};
process.stdout.write(JSON.stringify(output));
